/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BottomPannel: typeof import('./src/components/chats/BottomPannel.vue')['default']
    ChatBottomPannel: typeof import('./src/components/chat/ChatBottomPannel.vue')['default']
    ChatMessageBlock: typeof import('./src/components/chat/ChatMessageBlock.vue')['default']
    ChatMessagesScroll: typeof import('./src/components/chat/ChatMessagesScroll.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    MyContainer: typeof import('./src/components/shared/myContainer.vue')['default']
    MyScreenLoader: typeof import('./src/components/shared/myScreenLoader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextArea: typeof import('./src/components/TextArea.vue')['default']
  }
}
