/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    ChatBottomPannel: typeof import('./src/components/chat/ChatBottomPannel.vue')['default']
    ChatMessageBlock: typeof import('./src/components/chat/ChatMessageBlock.vue')['default']
    ChatMessagesScroll: typeof import('./src/components/chat/ChatMessagesScroll.vue')['default']
    ChatsList: typeof import('./src/components/chatsList/ChatsList.vue')['default']
    ChatsListItem: typeof import('./src/components/chatsList/ChatsListItem.vue')['default']
    ChatStartNew: typeof import('./src/components/chat/ChatStartNew.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ModelCard: typeof import('./src/components/models/ModelCard.vue')['default']
    ModelFileCard: typeof import('./src/components/models/ModelFileCard.vue')['default']
    MyContainer: typeof import('./src/components/shared/myContainer.vue')['default']
    MyIconButton: typeof import('./src/components/shared/MyIconButton.vue')['default']
    MyScreenLoader: typeof import('./src/components/shared/myScreenLoader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextArea: typeof import('./src/components/TextArea.vue')['default']
  }
}
